### ISSUE TITLE
Cursor stops working on other applications

### ISSUE THREAD

**Issue by homonecloco** [Uauy-Lab/pangenome-web#3]
As soon as you click on a block then it disappears and does not come back unless you go to another programme (like powerpoint), click on it and then return to the browser… but as soon as you click on a block then the cursor/line with the position goes away, and so does the ability to highlight a genotype at one position (you can still highlight the genotype across all blocks in the window, but you can’t recover the functionality of scrolling across and seeing the blocks shift as you move). Added later: I noticed that if you have the window in powerpoint, or any other programme, and then you just move the mouse, but not click on the screen then the cursor works..

**Comment by homonecloco** [comment]
@uauy I don't understand. The version online shouldn't do anything when you click on a block. The previous version was highlightn that position. But now it is doing it when you move the mouse in the block. What is the expected behaviour? 

The behaviour that you are seeing when looking on other applications is dependent on the browser, operating system and energy saving options. Browsers may disable the code execution of a page in the background.

**Comment by uauy** [comment]
@homonecloco the issue is that when I am using the page (i.e. I click anywhere on the screen so that I am actively on the website rather than being on another programme), the cursor and smoothness of the page dissappear.. so the cursor comes and goes as I move across a chromosome and the position also comes and goes... this does not happen when I click on another programme and slide my mouse to the haplotype webpage... I can show you when we speak
